apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
stringData:
  mongo-username: "YWRtaW4K"
  mongo-password: "cGFzc3dvcmQK"  
  mongo-uri: "mongodb://admin:password@mongo:27017/todo_db?authSource=admin"