apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: Zerosploit
  template:
    metadata:
      labels:
        app: Zerosploit
    spec:
      containers:
      - name: hello-world
        image: alyesmaeil/zerospolit-testing-img:latest
        ports:
        - containerPort: 80  